#define LINUX 
#define PVR_BUILD_DIR "jz4780_android"
#define PVR_BUILD_TYPE "release"
#define PVRSRV_MODNAME "pvrsrvkm"
#define SGXCORE 540
#define SGX540 
#define SUPPORT_SGX540 
#define SUPPORT_SGX 
#define SGX_CORE_REV 130
#define TRANSFER_QUEUE 
#define PVR_SECURE_HANDLES 
#define SUPPORT_LISR_MISR_SYNC 
#define PVR_LINUX_MEM_AREA_POOL_MAX_PAGES 5400
#define PVR_LINUX_MEM_AREA_USE_VMAP 
#define PVR_LINUX_MEM_AREA_POOL_ALLOW_SHRINK 
// #define DEBUG
// #define DEBUG_LINUX_MEMORY_ALLOCATIONS
// #define DEBUG_LINUX_MEM_AREAS
// #define DEBUG_LINUX_MMAP_AREAS
// #define DEBUG_BRIDGE_KM
#define SUPPORT_PERCONTEXT_PB 
#define SUPPORT_HW_RECOVERY 
#define SUPPORT_ACTIVE_POWER_MANAGEMENT 
#define SUPPORT_SGX_HWPERF 
#define SUPPORT_SGX_LOW_LATENCY_SCHEDULING 
#define SUPPORT_MEMINFO_IDS 
#define SUPPORT_SGX_NEW_STATUS_VALS 
#define SUPPORT_DBGDRV_EVENT_OBJECTS 
#define SGX_FEATURE_SYSTEM_CACHE 
#define SGX_FAST_DPM_INIT 
#define PVRSRV_USSE_EDM_STATUS_DEBUG 
#define SYS_USING_INTERRUPTS 
#define PVRSRV_NEW_PVR_DPF 
#define SUPPORT_ION 
#define SUPPORT_DMABUF 
#define IMG_ADDRSPACE_PHYSADDR_BITS 32
#define SUPPORT_LINUX_X86_WRITECOMBINE 
#define SUPPORT_LINUX_X86_PAT 
#define SGX_DYNAMIC_TIMING_INFO 
#define SYS_CUSTOM_POWERLOCK_WRAP 
#define PVR_LINUX_USING_WORKQUEUES 
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE 
#define PVR_LINUX_TIMERS_USING_WORKQUEUES 
#define LDM_PLATFORM 
#define PVR_LDM_DEVICE_TREE 
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVRSRV_DUMP_MK_TRACE 
#define SUPPORT_LARGE_GENERAL_HEAP 
#define ANDROID 
#define PVR_ANDROID_NATIVE_WINDOW_HAS_SYNC 
#define SUPPORT_ION_HEADER "../drivers/staging/android/ion/ion.h"
#define SUPPORT_ION_PRIV_HEADER "../drivers/staging/android/ion/ion_priv.h"
#define SUPPORT_ION_USE_SG_LENGTH 
#define SUPPORT_DRI_DRM 
#define PVR_DRI_DRM_PLATFORM_DEV 
